# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be281566e92d18d89be58eaae8574542b8ba791d31cbbc345e73910dd33ba298683a82da625e5ce898d959f953d70c5695c53d9f384a7e615fd1a77c69c75648

test:
  secret_key_base: c7946f6381313471d81e43b051e9aab132bfaa379119612c3db30531c3080f01d9ca9d0fae4836056fb966508f7b894cca8c4518392d4bbd7de62319b47fe6ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
